### PR TITLE
Add initial test and test set-up

### PR DESCRIPTION
**Pull request by MollyJeanB**
config still broken

### CODE REVIEW

**Comment by MollyJeanB** [comment]
https://stackoverflow.com/questions/54461150/jest-not-parsing-es6-syntaxerror-unexpected-token-import
https://github.com/facebook/jest/issues/6933

**Comment by MollyJeanB** [comment]
I added a jest config. This guide may be helpful:

https://dev.to/ivadyhabimana/setup-jest-and-react-testing-library-in-a-react-project-a-step-by-step-guide-1mf0

**Comment by MollyJeanB** [comment]
The issues with chance may be regarding node version

**Comment by MollyJeanB** [comment]
So I think the best course of action at this point would probably be to remove any setup files and packages related to jest and react testing library, and then re-install and reconfigure based on something like [this guide](https://dev.to/ivadyhabimana/setup-jest-and-react-testing-library-in-a-react-project-a-step-by-step-guide-1mf0)  though it won't be that exactly because of TypeScript. I may be able to take a stab at that for you today if I have time

**Comment by MollyJeanB** [comment]
ok so! I got the test running locally for me.  @hana-acciaioli @emilysellers  go ahead and check out this branch, install dependencies, and see if you can run `yarn test` in the terminal and see the test pass. 

Note: I'm running for node v16.13.0 for this project. If you're on a different version (run `node -v` in the terminal to find out) that may cause issues with install dependencies. If that's the case I can adjust package version on this to work it out

**Comment by hana-acciaioli** [comment]
Successfully tested on my local machine. Thank you so much @MollyJeanB .

**Comment by emilysellers** [comment]
Running successfully for me as well - thank you @MollyJeanB!

**Pull request merged**
